package com.dadcoach.memory;

/**
 * Source type indicating how a memory was created.
 *
 * <p>From SPEC-004 Requirement 3:
 * Each memory is tagged with its source type to support
 * provenance tracking, confidence calibration, and audit requirements.
 */
public enum MemorySourceType {

    /**
     * Memory was automatically extracted from a conversation transcript.
     * Subject to AI recommendation validation before persistence.
     */
    CONVERSATION_EXTRACTION,

    /**
     * Memory was collected during the onboarding flow.
     * Typically has high confidence (1.0) as it comes from structured input.
     */
    ONBOARDING,

    /**
     * Memory was created from an explicit correction by the father.
     * Always has confidence 1.0 and may supersede existing memories.
     */
    FATHER_CORRECTION,

    /**
     * Memory was generated by the system (summaries, milestones).
     * Examples: CONVERSATION_SUMMARY memories, streak milestone memories.
     */
    SYSTEM_GENERATED,

    /**
     * Memory was derived from a mission completion outcome.
     * Confidence based on mission outcome quality and reflection content.
     */
    MISSION_OUTCOME
}
