import { expect, test } from '@playwright/test'
import { seedAwaitingFather, seedYoav, signIn, sql } from './fixtures'

test('home is his week: goal, done vs planned, next session, belt', async ({ page }) => {
  const yoav = seedYoav()
  await signIn(page, yoav.phone)
  await expect(page.getByText('היעד שלך השבוע')).toBeVisible()
  await expect(page.getByText('שעה', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('מתוך 3 שעות')).toBeVisible()
  await expect(page.getByText('חסרות עוד')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'חגורה צהובה' })).toBeVisible()
  await expect(page.getByText('עוד 6 מפגשים לחגורה כתומה')).toBeVisible()
  await expect(page.locator('section', { has: page.getByRole('heading', { name: 'המפגש הבא' }) }).getByText('איתי')).toBeVisible()
  await expect(page.getByRole('link', { name: 'דבר עם המאמן בוואטסאפ' })).toHaveAttribute('href', /^https:\/\/wa\.me\/19995550100\?text=/)
})

test('"it happened" from the home credits the week', async ({ page }) => {
  const dan = seedAwaitingFather('דן')
  await signIn(page, dan.phone)
  await expect(page.getByRole('heading', { name: 'מחכה לאישור שלך' })).toBeVisible()
  await page.getByRole('button', { name: 'היה!' }).click()
  await page.getByLabel('מה עשיתם? (לא חובה)').fill('קראנו ספר')
  await page.getByRole('button', { name: 'כן, היה' }).click()
  await expect(page.getByText('נספרו לשבוע')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'מחכה לאישור שלך' })).toHaveCount(0)
  expect(sql(`SELECT status || ':' || completion_notes FROM quality_time WHERE id = '${dan.session}';`)).toBe('COMPLETED:קראנו ספר')
})

test('sessions: tabs and cancelling an upcoming one', async ({ page }) => {
  const yoav = seedYoav()
  await signIn(page, yoav.phone)
  await page.getByRole('link', { name: 'מפגשים' }).first().click()
  await expect(page.getByRole('heading', { name: 'מפגשים', level: 1 })).toBeVisible()
  await page.getByRole('radio', { name: /^היו/ }).check()
  await expect(page.getByText('בנינו מגדל לגו ענק', { exact: false })).toBeVisible()
  await page.getByRole('radio', { name: /^קרובים/ }).check()
  await page.getByRole('button', { name: 'ביטול' }).first().click()
  await page.getByRole('button', { name: 'כן, לבטל' }).click()
  await expect(page.getByText('המפגש בוטל')).toBeVisible()
  await expect(page.getByText('אין מפגשים קרובים')).toBeVisible()
})

test('children: add one, edit one', async ({ page }) => {
  const yoav = seedYoav()
  await signIn(page, yoav.phone)
  await page.goto('/children')
  await expect(page.getByText('נועה')).toBeVisible()
  await page.getByRole('button', { name: 'הוספת ילד' }).click()
  await page.getByLabel('שם').fill('גאיה')
  await page.getByLabel('גיל').fill('2')
  await page.getByRole('button', { name: 'שמירה' }).click()
  await expect(page.getByText('גאיה ברשימה.')).toBeVisible()
  await expect(page.getByText('גיל שנתיים')).toBeVisible()
  await page.getByRole('button', { name: 'עריכת איתי' }).click()
  await page.getByLabel('גיל').fill('5')
  await page.getByRole('button', { name: 'שמירה' }).click()
  await expect(page.getByText('גיל 5')).toBeVisible()
})

test('progress and settings; deleting his data needs the typed word', async ({ page }) => {
  const yoav = seedYoav()
  await signIn(page, yoav.phone)
  await page.goto('/progress')
  await expect(page.getByRole('heading', { name: 'הישגים' })).toBeVisible()
  await expect(page.getByText('המפגש הראשון', { exact: true })).toBeVisible()
  await page.goto('/settings')
  await page.getByLabel('איך לקרוא לך').fill('יואב לוי')
  await page.getByRole('button', { name: 'שמירה' }).click()
  await expect(page.getByText('נשמר.')).toBeVisible()
  await page.getByRole('button', { name: 'מחיקת הנתונים שלי' }).click()
  const confirm = page.getByRole('button', { name: 'מחיקה לצמיתות' })
  await expect(confirm).toBeDisabled()
  await page.getByLabel(/כדי לאשר/).fill('מחיקה')
  await confirm.click()
  await expect(page).toHaveURL(/\/login$/)
  await expect(page.getByText('בקשת המחיקה התקבלה')).toBeVisible()
  expect(sql(`SELECT status FROM father WHERE id = ${yoav.id};`)).toBe('DELETED')
})
